# Generated by Django 5.2.16 on 2026-08-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        ("estimates", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsnapshot",
            name="estimate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_snapshot",
                to="estimates.estimate",
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="workspaces.business",
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="estimate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_deliveries",
                to="estimates.estimate",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="workspaces.business",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="estimate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_assets",
                to="estimates.estimate",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_assets",
                to="communications.documentsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbox_events",
                to="workspaces.business",
            ),
        ),
        migrations.AddField(
            model_name="publicdocumentlink",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_records",
                to="workspaces.business",
            ),
        ),
        migrations.AddField(
            model_name="publicdocumentlink",
            name="estimate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_links",
                to="estimates.estimate",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["status", "available_at"], name="communicati_status_8ba8f1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("processed_at__isnull", False), ("status", "completed")),
                    models.Q(
                        models.Q(("status", "completed"), _negated=True),
                        ("processed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="communications_outbox_completion_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="publicdocumentlink",
            index=models.Index(
                fields=["business", "estimate", "purpose", "revoked_at"],
                name="communicati_busines_76bc4e_idx",
            ),
        ),
    ]
