# Generated by Django 5.2.16 on 2026-08-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0002_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsnapshot",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_snapshot",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_deliveries",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="kind",
            field=models.CharField(
                choices=[
                    ("estimate", "Estimate"),
                    ("invoice", "Invoice"),
                    ("reminder", "Invoice reminder"),
                    ("receipt", "Payment receipt"),
                ],
                default="estimate",
                max_length=20,
            ),
        ),
    ]
