# Generated by Django 5.2.16 on 2026-08-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "communications",
            "0003_documentsnapshot_invoice_emaildelivery_invoice_and_more",
        ),
        (
            "estimates",
            "0004_remove_estimate_estimates_estimate_acceptance_state_consistent_and_more",
        ),
        ("invoices", "0001_initial"),
        ("payments", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_deliveries",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_assets",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_assets",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="publicdocumentlink",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_links",
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="documentsnapshot",
            name="estimate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_snapshot",
                to="estimates.estimate",
            ),
        ),
        migrations.AlterField(
            model_name="emaildelivery",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_deliveries",
                to="estimates.estimate",
            ),
        ),
        migrations.AlterField(
            model_name="fileasset",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_assets",
                to="estimates.estimate",
            ),
        ),
        migrations.AlterField(
            model_name="fileasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("estimate_pdf", "Estimate PDF"),
                    ("invoice_pdf", "Invoice PDF"),
                    ("payment_receipt", "Payment receipt"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fileasset",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_assets",
                to="communications.documentsnapshot",
            ),
        ),
        migrations.AlterField(
            model_name="publicdocumentlink",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_links",
                to="estimates.estimate",
            ),
        ),
        migrations.AddIndex(
            model_name="publicdocumentlink",
            index=models.Index(
                fields=["business", "invoice", "purpose", "revoked_at"],
                name="communicati_busines_b8bd95_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estimate__isnull", False), ("invoice__isnull", True)),
                    models.Q(("estimate__isnull", True), ("invoice__isnull", False)),
                    _connector="OR",
                ),
                name="communications_snapshot_exactly_one_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estimate__isnull", False),
                        ("invoice__isnull", True),
                        ("payment__isnull", True),
                    ),
                    models.Q(
                        ("estimate__isnull", True),
                        ("invoice__isnull", False),
                        ("payment__isnull", True),
                    ),
                    models.Q(
                        ("estimate__isnull", True),
                        ("invoice__isnull", True),
                        ("payment__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="communications_delivery_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estimate__isnull", False),
                        ("invoice__isnull", True),
                        ("payment__isnull", True),
                    ),
                    models.Q(
                        ("estimate__isnull", True),
                        ("invoice__isnull", False),
                        ("payment__isnull", True),
                    ),
                    models.Q(
                        ("estimate__isnull", True),
                        ("invoice__isnull", True),
                        ("payment__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="communications_file_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicdocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estimate__isnull", False), ("invoice__isnull", True)),
                    models.Q(("estimate__isnull", True), ("invoice__isnull", False)),
                    _connector="OR",
                ),
                name="communications_link_exactly_one_document",
            ),
        ),
    ]
