# Generated by Django 5.2.16 on 2026-08-12 22:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0004_emaildelivery_payment_fileasset_invoice_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("estimate_accepted", "Estimate accepted"),
                            ("estimate_declined", "Estimate declined"),
                            ("payment_received", "Payment received"),
                            ("invoice_overdue", "Invoice overdue"),
                            ("delivery_failed", "Delivery failed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(max_length=500)),
                ("target_path", models.CharField(blank=True, max_length=500)),
                ("dedupe_key", models.CharField(max_length=180)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["business", "recipient", "read_at"],
                        name="communicati_busines_9a6378_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "dedupe_key"),
                        name="communications_notification_business_dedupe_unique",
                    )
                ],
            },
        ),
    ]
