# Generated by Django 5.2.16 on 2026-08-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0005_notification"),
        (
            "estimates",
            "0004_remove_estimate_estimates_estimate_acceptance_state_consistent_and_more",
        ),
        ("invoices", "0002_remove_invoice_invoices_invoice_amounts_valid_and_more"),
        ("payments", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emaildelivery",
            index=models.Index(
                fields=["business", "status", "created_at"],
                name="communicati_busines_83fdc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildelivery",
            index=models.Index(
                fields=["business", "kind", "created_at"],
                name="communicati_busines_070592_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["business", "status", "available_at"],
                name="communicati_busines_1ae2ea_idx",
            ),
        ),
    ]
