# Generated by Django 5.2.16 on 2026-08-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_emaildelivery_communicati_busines_83fdc6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicdocumentlink',
            name='purpose',
            field=models.CharField(choices=[('view', 'View'), ('respond', 'View and respond'), ('pay', 'Pay')], max_length=20),
        ),
    ]
