# Generated by Django 5.2.16 on 2026-08-12 23:25

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_publicdocumentlink_purpose'),
        ('invoices', '0002_remove_invoice_invoices_invoice_amounts_valid_and_more'),
        ('payments', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_event_id', models.CharField(max_length=255, unique=True)),
                ('connected_account_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=120)),
                ('livemode', models.BooleanField(default=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('signature_verified_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_co_status_af6720_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_account_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Onboarding pending'), ('restricted', 'Restricted'), ('ready', 'Ready'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('details_submitted', models.BooleanField(default=False)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('requirements_due', models.JSONField(blank=True, default=list)),
                ('disabled_reason', models.CharField(blank=True, max_length=255)),
                ('provider_synced_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='workspaces.business')),
            ],
            options={
                'ordering': ('business_id',),
                'constraints': [models.UniqueConstraint(fields=('business',), name='payments_connected_account_business_unique'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), models.Q(('charges_enabled', True), ('details_submitted', True), ('payouts_enabled', True)), _connector='OR'), name='payments_connected_account_ready_consistent')],
            },
        ),
        migrations.CreateModel(
            name='InvoicePaymentAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Creating checkout'), ('open', 'Awaiting payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('provider_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='workspaces.business')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_attempts', to='invoices.invoice')),
                ('public_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='communications.publicdocumentlink')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business', 'invoice', 'status'], name='payments_in_busines_e3287c_idx'), models.Index(fields=['status', 'expires_at'], name='payments_in_status_87cae0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_attempt_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='payments_attempt_completion_consistent')],
            },
        ),
    ]
