# Generated by Django 5.2.16 on 2026-08-12 15:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import workspaces.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("website", models.URLField(blank=True)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=120)),
                ("postal_code", models.CharField(max_length=30)),
                ("country_code", models.CharField(default="US", max_length=2)),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar (USD)"),
                            ("CAD", "Canadian Dollar (CAD)"),
                            ("EUR", "Euro (EUR)"),
                            ("GBP", "Pound Sterling (GBP)"),
                            ("AUD", "Australian Dollar (AUD)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/New_York",
                        max_length=64,
                        validators=[workspaces.models.validate_timezone],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "businesses",
                "ordering": ("display_name", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estimate_prefix",
                    models.CharField(
                        default="EST-",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 1-12 uppercase letters, numbers, or hyphens.",
                                regex="^[A-Z0-9-]{1,12}$",
                            )
                        ],
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="INV-",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 1-12 uppercase letters, numbers, or hyphens.",
                                regex="^[A-Z0-9-]{1,12}$",
                            )
                        ],
                    ),
                ),
                (
                    "default_payment_terms_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[django.core.validators.MaxValueValidator(365)],
                    ),
                ),
                (
                    "default_estimate_expiration_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[django.core.validators.MaxValueValidator(365)],
                    ),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("default_invoice_notes", models.TextField(blank=True)),
                ("default_invoice_terms", models.TextField(blank=True)),
                ("default_estimate_notes", models.TextField(blank=True)),
                ("default_estimate_terms", models.TextField(blank=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to="workspaces.business",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "business settings",
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="business",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="businesses",
                to="workspaces.workspace",
            ),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("workspace_id", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "user"),
                        name="workspaces_membership_workspace_user_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "owner"), ("status", "active")),
                        fields=("workspace",),
                        name="workspaces_membership_one_active_owner",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["workspace", "is_active"], name="workspaces__workspa_1a7aae_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True), ("is_active", True)),
                fields=("workspace",),
                name="workspaces_business_one_active_per_workspace",
            ),
        ),
    ]
