# Generated by Django 5.2.16 on 2026-08-17 00:53

import django.core.validators
from django.db import migrations, models

import workspaces.models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to=workspaces.models.business_logo_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg", "jpeg")
                    ),
                    workspaces.models.validate_business_logo,
                ],
            ),
        ),
    ]
