# Generated by Django 5.2.16 on 2026-08-12 15:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("estimate", "Estimate"), ("invoice", "Invoice")],
                        max_length=20,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 1-12 uppercase letters, numbers, or hyphens.",
                                regex="^[A-Z0-9-]{1,12}$",
                            )
                        ],
                    ),
                ),
                ("next_value", models.PositiveBigIntegerField(default=1001)),
                (
                    "padding_width",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_sequences",
                        to="workspaces.business",
                    ),
                ),
            ],
            options={
                "ordering": ("business_id", "document_type"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "document_type"),
                        name="core_document_sequence_business_type_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("next_value__gt", 0)),
                        name="core_document_sequence_next_value_positive",
                    ),
                ],
            },
        ),
    ]
