# Generated by Django 5.2.16 on 2026-08-12 18:12

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("crm", "0001_initial"),
        (
            "estimates",
            "0004_remove_estimate_estimates_estimate_acceptance_state_consistent_and_more",
        ),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed amount"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "deposit_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="crm.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_estimate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="estimates.estimate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit_rate", models.DecimalField(decimal_places=4, max_digits=14)),
                ("is_taxable", models.BooleanField(default=False)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "allocated_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "source_catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_line_items",
                        to="catalog.productservice",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["business", "status", "created_at"],
                name="invoices_in_busines_7908aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["business", "contact", "created_at"],
                name="invoices_in_busines_b45269_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["business", "due_date"], name="invoices_in_busines_dbc42f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("business", "number"),
                name="invoices_invoice_business_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_value__gte", 0),
                    ("subtotal__gte", 0),
                    ("discount_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("total__gte", 0),
                    ("deposit_required__gte", 0),
                    ("amount_paid__gte", 0),
                    ("balance_due__gte", 0),
                    ("discount_amount__lte", models.F("subtotal")),
                    ("deposit_required__lte", models.F("total")),
                    ("amount_paid__lte", models.F("total")),
                    (
                        "balance_due",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total"), "-", models.F("amount_paid")
                        ),
                    ),
                ),
                name="invoices_invoice_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("issued_at__isnull", True), ("number", ""), ("status", "draft")
                    ),
                    models.Q(
                        models.Q(("status", "draft"), _negated=True),
                        models.Q(("number", ""), _negated=True),
                        ("issued_at__isnull", False),
                        ("issue_date__isnull", False),
                        ("due_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="invoices_invoice_issue_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "void"), ("voided_at__isnull", False)),
                    models.Q(
                        models.Q(("status", "void"), _negated=True),
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="invoices_invoice_void_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("issue_date__isnull", True),
                    ("due_date__isnull", True),
                    ("due_date__gte", models.F("issue_date")),
                    _connector="OR",
                ),
                name="invoices_invoice_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelineitem",
            constraint=models.UniqueConstraint(
                fields=("invoice", "position"),
                name="invoices_line_invoice_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gt", 0),
                    ("unit_rate__gte", 0),
                    ("tax_rate__gte", 0),
                    ("tax_rate__lte", 100),
                    ("line_subtotal__gte", 0),
                    ("allocated_discount__gte", 0),
                    ("taxable_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("line_total__gte", 0),
                ),
                name="invoices_line_amounts_valid",
            ),
        ),
    ]
