# Generated by Django 5.2.16 on 2026-08-12 18:15

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        (
            "estimates",
            "0004_remove_estimate_estimates_estimate_acceptance_state_consistent_and_more",
        ),
        ("invoices", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoices_invoice_amounts_valid",
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoices_invoice_void_state_consistent",
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_value__gte", 0),
                    ("subtotal__gte", 0),
                    ("discount_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("total__gte", 0),
                    ("deposit_required__gte", 0),
                    ("amount_paid__gte", 0),
                    ("balance_due__gte", 0),
                    ("discount_amount__lte", models.F("subtotal")),
                    models.Q(
                        ("status", "draft"),
                        ("deposit_required__lte", models.F("total")),
                        _connector="OR",
                    ),
                    ("amount_paid__lte", models.F("total")),
                    (
                        "balance_due",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total"), "-", models.F("amount_paid")
                        ),
                    ),
                ),
                name="invoices_invoice_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "void"),
                        ("voided_at__isnull", False),
                        models.Q(("void_reason", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("status", "void"), _negated=True),
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="invoices_invoice_void_state_consistent",
            ),
        ),
    ]
