# Generated by Django 5.2.16 on 2026-08-12 15:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("contact.created", "Contact created"),
                            ("contact.updated", "Contact updated"),
                            ("contact.status_changed", "Contact status changed"),
                            ("contact.note_added", "Contact note added"),
                            ("catalog.created", "Catalog item created"),
                            ("catalog.updated", "Catalog item updated"),
                            ("catalog.status_changed", "Catalog status changed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_events",
                        to="workspaces.business",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-created_at"),
            },
        ),
    ]
