# Generated by Django 5.2.16 on 2026-08-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        ("catalog", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityevent",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_events",
                to="crm.contact",
            ),
        ),
        migrations.AddField(
            model_name="activityevent",
            name="product_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_events",
                to="catalog.productservice",
            ),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["business", "occurred_at"],
                name="activity_ac_busines_e22d03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["business", "event_type", "occurred_at"],
                name="activity_ac_busines_3deb7d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("contact__isnull", False), ("product_service__isnull", True)
                    ),
                    models.Q(
                        ("contact__isnull", True), ("product_service__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="activity_event_exactly_one_target",
            ),
        ),
    ]
