# Generated by Django 5.2.16 on 2026-08-12 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activityevent",
            name="activity_event_exactly_one_target",
        ),
    ]
