# Generated by Django 5.2.16 on 2026-08-12 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_activityevent_estimate_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activityevent",
            name="activity_event_exactly_one_target",
        ),
    ]
