# Generated by Django 5.2.16 on 2026-08-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_remove_activityevent_activity_event_exactly_one_target"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityevent",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_events",
                to="invoices.invoice",
            ),
        ),
    ]
