# Generated by Django 5.2.16 on 2026-08-12 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0006_activityevent_invoice"),
        ("catalog", "0001_initial"),
        ("crm", "0001_initial"),
        (
            "estimates",
            "0004_remove_estimate_estimates_estimate_acceptance_state_consistent_and_more",
        ),
        ("invoices", "0001_initial"),
        ("payments", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activityevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_events",
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="activityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("contact.created", "Contact created"),
                    ("contact.updated", "Contact updated"),
                    ("contact.status_changed", "Contact status changed"),
                    ("contact.note_added", "Contact note added"),
                    ("catalog.created", "Catalog item created"),
                    ("catalog.updated", "Catalog item updated"),
                    ("catalog.status_changed", "Catalog status changed"),
                    ("estimate.created", "Estimate created"),
                    ("estimate.updated", "Estimate updated"),
                    ("estimate.line_changed", "Estimate line changed"),
                    ("estimate.issued", "Estimate issued"),
                    ("estimate.email_queued", "Estimate email queued"),
                    ("estimate.viewed", "Estimate viewed"),
                    ("estimate.accepted", "Estimate accepted"),
                    ("estimate.declined", "Estimate declined"),
                    ("estimate.converted", "Estimate converted"),
                    ("invoice.created", "Invoice created"),
                    ("invoice.line_changed", "Invoice line changed"),
                    ("invoice.issued", "Invoice issued"),
                    ("invoice.email_queued", "Invoice email queued"),
                    ("invoice.reminder_queued", "Reminder queued"),
                    ("invoice.viewed", "Invoice viewed"),
                    ("invoice.voided", "Invoice voided"),
                    ("payment.posted", "Payment posted"),
                    ("payment.reversed", "Payment reversed"),
                    ("payment.receipt_queued", "Receipt queued"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="activityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("contact__isnull", False),
                        ("estimate__isnull", True),
                        ("invoice__isnull", True),
                        ("payment__isnull", True),
                        ("product_service__isnull", True),
                    ),
                    models.Q(
                        ("contact__isnull", True),
                        ("estimate__isnull", True),
                        ("invoice__isnull", True),
                        ("payment__isnull", True),
                        ("product_service__isnull", False),
                    ),
                    models.Q(
                        ("contact__isnull", True),
                        ("estimate__isnull", False),
                        ("invoice__isnull", True),
                        ("payment__isnull", True),
                        ("product_service__isnull", True),
                    ),
                    models.Q(
                        ("contact__isnull", True),
                        ("estimate__isnull", True),
                        ("invoice__isnull", False),
                        ("payment__isnull", True),
                        ("product_service__isnull", True),
                    ),
                    models.Q(
                        ("contact__isnull", True),
                        ("estimate__isnull", True),
                        ("invoice__isnull", True),
                        ("payment__isnull", False),
                        ("product_service__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="activity_event_exactly_one_target",
            ),
        ),
    ]
