# Generated by Django 5.2.16 on 2026-08-12 16:18

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("crm", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("converted", "Converted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed amount"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "deposit_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed amount"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "deposit_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("requires_acceptance", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "deposit_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimates",
                        to="crm.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EstimateAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("in_person", "In person"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accepted_by_name", models.CharField(blank=True, max_length=255)),
                ("accepted_by_email", models.EmailField(blank=True, max_length=254)),
                (
                    "accepted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("terms_snapshot", models.TextField(blank=True)),
                (
                    "total_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimate_acceptances",
                        to="workspaces.business",
                    ),
                ),
                (
                    "estimate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance",
                        to="estimates.estimate",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_estimate_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-accepted_at",),
            },
        ),
        migrations.CreateModel(
            name="EstimateLineItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit_rate", models.DecimalField(decimal_places=4, max_digits=14)),
                ("is_taxable", models.BooleanField(default=False)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "allocated_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_items",
                        to="estimates.estimate",
                    ),
                ),
                (
                    "source_catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimate_line_items",
                        to="catalog.productservice",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="estimate",
            index=models.Index(
                fields=["business", "status", "created_at"],
                name="estimates_e_busines_734e55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="estimate",
            index=models.Index(
                fields=["business", "contact", "created_at"],
                name="estimates_e_busines_75b6cf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("business", "number"),
                name="estimates_estimate_business_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_value__gte", 0),
                    ("deposit_value__gte", 0),
                    ("subtotal__gte", 0),
                    ("discount_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("total__gte", 0),
                    ("deposit_required__gte", 0),
                    ("discount_amount__lte", models.F("subtotal")),
                    ("deposit_required__lte", models.F("total")),
                ),
                name="estimates_estimate_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("issued_at__isnull", True), ("number", ""), ("status", "draft")
                    ),
                    models.Q(
                        models.Q(("status", "draft"), _negated=True),
                        models.Q(("number", ""), _negated=True),
                        ("issued_at__isnull", False),
                        ("issue_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="estimates_estimate_issue_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "accepted"), ("accepted_at__isnull", False)),
                    models.Q(
                        models.Q(("status", "accepted"), _negated=True),
                        ("accepted_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="estimates_estimate_acceptance_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "declined"), ("declined_at__isnull", False)),
                    models.Q(
                        models.Q(("status", "declined"), _negated=True),
                        ("declined_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="estimates_estimate_decline_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimatelineitem",
            constraint=models.UniqueConstraint(
                fields=("estimate", "position"),
                name="estimates_line_estimate_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimatelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gt", 0),
                    ("unit_rate__gte", 0),
                    ("tax_rate__gte", 0),
                    ("tax_rate__lte", 100),
                    ("line_subtotal__gte", 0),
                    ("allocated_discount__gte", 0),
                    ("taxable_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("line_total__gte", 0),
                ),
                name="estimates_line_amounts_valid",
            ),
        ),
    ]
