# Generated by Django 5.2.16 on 2026-08-12 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        (
            "estimates",
            "0002_remove_estimate_estimates_estimate_acceptance_state_consistent_and_more",
        ),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("issue_date__isnull", True),
                    ("expiration_date__isnull", True),
                    ("expiration_date__gte", models.F("issue_date")),
                    _connector="OR",
                ),
                name="estimates_estimate_dates_valid",
            ),
        ),
    ]
