# Generated by Django 5.2.16 on 2026-08-12 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        ("estimates", "0003_estimate_estimates_estimate_dates_valid"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="estimate",
            name="estimates_estimate_acceptance_state_consistent",
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "accepted"), ("accepted_at__isnull", False)),
                    ("status", "converted"),
                    models.Q(
                        models.Q(
                            ("status__in", ("accepted", "converted")), _negated=True
                        ),
                        ("accepted_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="estimates_estimate_acceptance_state_consistent",
            ),
        ),
    ]
