# Generated by Django 5.2.16 on 2026-08-12 15:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=30)),
                ("country_code", models.CharField(default="US", max_length=2)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("client", "Client"),
                            ("archived", "Archived"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                (
                    "status_before_archive",
                    models.CharField(
                        blank=True,
                        choices=[("lead", "Lead"), ("client", "Client")],
                        max_length=20,
                    ),
                ),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("last_name", "first_name", "company_name", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ContactNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_notes",
                        to="crm.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contact_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["business", "status", "last_name", "first_name"],
                name="crm_contact_busines_418fa8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["business", "company_name"],
                name="crm_contact_busines_75791d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("archived_at__isnull", True),
                        ("converted_at__isnull", True),
                        ("status", "lead"),
                        ("status_before_archive", ""),
                    ),
                    models.Q(
                        ("archived_at__isnull", True),
                        ("converted_at__isnull", False),
                        ("status", "client"),
                        ("status_before_archive", ""),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("converted_at__isnull", True),
                        ("status", "archived"),
                        ("status_before_archive", "lead"),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("converted_at__isnull", False),
                        ("status", "archived"),
                        ("status_before_archive", "client"),
                    ),
                    _connector="OR",
                ),
                name="crm_contact_lifecycle_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="contactnote",
            index=models.Index(
                fields=["business", "contact", "created_at"],
                name="crm_contact_busines_d2dd63_idx",
            ),
        ),
    ]
