# Generated by Django 5.2.16 on 2026-08-12 15:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductService",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("service", "Service"), ("product", "Product")],
                        default="service",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("service", "Service"),
                            ("square_foot", "Square foot"),
                            ("linear_foot", "Linear foot"),
                            ("custom", "Custom"),
                        ],
                        default="service",
                        max_length=30,
                    ),
                ),
                ("custom_unit", models.CharField(blank=True, max_length=40)),
                (
                    "default_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_taxable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="workspaces.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_catalog_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["business", "is_active", "item_type", "name"],
                        name="catalog_pro_busines_22df9a_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("default_rate__gte", 0)),
                        name="catalog_product_service_rate_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("unit", "custom"),
                                models.Q(("custom_unit", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("unit", "custom"), _negated=True),
                                ("custom_unit", ""),
                            ),
                            _connector="OR",
                        ),
                        name="catalog_product_service_custom_unit_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("archived_at__isnull", True), ("is_active", True)
                            ),
                            models.Q(
                                ("archived_at__isnull", False), ("is_active", False)
                            ),
                            _connector="OR",
                        ),
                        name="catalog_product_service_archive_consistent",
                    ),
                ],
            },
        ),
    ]
