# Generated by Django 5.2.16 on 2026-08-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productservice",
            name="default_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
